branches:
  only:
    - cn
language: node_js
node_js:
  - "8"
sudo: required
install:
  - npm install --global yarn
  - yarn
  - sudo pip install proselint
before_script:
  - source ./src/scripts/env.sh
script:
  - bash ./src/scripts/deploy.sh
